// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmsairtfwupgudexwsjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtc2FpcnRmd3VwZ3VkZXh3c2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0Njg1NTIsImV4cCI6MjA1NjA0NDU1Mn0.JtAlCVOjDZuLBPrdCXaMwDFCb80edVb6z-Gf3GR0Ems";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);